# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from DialogsDesigns.CustomCalendar import CustomCalendar


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        MainWindow.setFont(font)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.centralwidget.setFont(font)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("background-color: rgb(228, 224, 220);")
        self.page.setObjectName("page")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.calendarWidget = CustomCalendar(self.page)
        self.calendarWidget.setObjectName("calendarWidget")
        self.horizontalLayout_9.addWidget(self.calendarWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.addFamilyMemberButton = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addFamilyMemberButton.setFont(font)
        self.addFamilyMemberButton.setAutoFillBackground(False)
        self.addFamilyMemberButton.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                                 "    border-style: outset;\n"
                                                 "    border-width: 2px;\n"
                                                 "    border-radius: 10px;\n"
                                                 "    border-color: rgb(0, 0, 0);\n"
                                                 "    font: bold 14px;\n"
                                                 "    min-width: 10em;\n"
                                                 "    padding: 6px;")
        self.addFamilyMemberButton.setFlat(False)
        self.addFamilyMemberButton.setObjectName("addFamilyMemberButton")
        self.verticalLayout.addWidget(self.addFamilyMemberButton)
        self.changeColorFamilyMember = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.changeColorFamilyMember.setFont(font)
        self.changeColorFamilyMember.setAutoFillBackground(False)
        self.changeColorFamilyMember.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                                   "    border-style: outset;\n"
                                                   "    border-width: 2px;\n"
                                                   "    border-radius: 10px;\n"
                                                   "    border-color: rgb(0, 0, 0);\n"
                                                   "    font: bold 14px;\n"
                                                   "    min-width: 10em;\n"
                                                   "    padding: 6px;")
        self.changeColorFamilyMember.setFlat(True)
        self.changeColorFamilyMember.setObjectName("changeColorFamilyMember")
        self.verticalLayout.addWidget(self.changeColorFamilyMember)
        self.removeFamilyMember = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.removeFamilyMember.setFont(font)
        self.removeFamilyMember.setAutoFillBackground(False)
        self.removeFamilyMember.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                              "    border-style: outset;\n"
                                              "    border-width: 2px;\n"
                                              "    border-radius: 10px;\n"
                                              "    border-color: rgb(0, 0, 0);\n"
                                              "    font: bold 14px;\n"
                                              "    min-width: 10em;\n"
                                              "    padding: 6px;")
        self.removeFamilyMember.setFlat(True)
        self.removeFamilyMember.setObjectName("removeFamilyMember")
        self.verticalLayout.addWidget(self.removeFamilyMember)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.addEventButton = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.addEventButton.setFont(font)
        self.addEventButton.setAutoFillBackground(False)
        self.addEventButton.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                          "    border-style: outset;\n"
                                          "    border-width: 2px;\n"
                                          "    border-radius: 10px;\n"
                                          "    border-color: rgb(0, 0, 0);\n"
                                          "    font: bold 14px;\n"
                                          "    min-width: 10em;\n"
                                          "    padding: 6px;")
        self.addEventButton.setFlat(True)
        self.addEventButton.setObjectName("addEventButton")
        self.verticalLayout.addWidget(self.addEventButton)
        self.toExcelButton = QtWidgets.QPushButton(self.page)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.toExcelButton.setFont(font)
        self.toExcelButton.setAutoFillBackground(False)
        self.toExcelButton.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                         "    border-style: outset;\n"
                                         "    border-width: 2px;\n"
                                         "    border-radius: 10px;\n"
                                         "    border-color: rgb(0, 0, 0);\n"
                                         "    font: bold 14px;\n"
                                         "    min-width: 10em;\n"
                                         "    padding: 6px;")
        self.toExcelButton.setFlat(True)
        self.toExcelButton.setObjectName("toExcelButton")
        self.verticalLayout.addWidget(self.toExcelButton)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("background-color: rgb(228, 224, 220);")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.radioButton = QtWidgets.QRadioButton(self.page_2)
        self.radioButton.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                       "    border-style: outset;\n"
                                       "    border-width: 2px;\n"
                                       "    border-radius: 10px;\n"
                                       "    border-color: rgb(0, 0, 0);\n"
                                       "    font: bold 14px;\n"
                                       "    min-width: 10em;\n"
                                       "    padding: 6px;")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.page_2)
        self.radioButton_2.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                         "    border-style: outset;\n"
                                         "    border-width: 2px;\n"
                                         "    border-radius: 10px;\n"
                                         "    border-color: rgb(0, 0, 0);\n"
                                         "    font: bold 14px;\n"
                                         "    min-width: 10em;\n"
                                         "    padding: 6px;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                   "    border-style: outset;\n"
                                   "    border-width: 2px;\n"
                                   "    border-radius: 10px;\n"
                                   "    border-color: rgb(0, 0, 0);\n"
                                   "    font: bold 14px;\n"
                                   "    min-width: 10em;\n"
                                   "    padding: 6px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.titleEdit = QtWidgets.QLineEdit(self.page_2)
        self.titleEdit.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                     "    border-style: outset;\n"
                                     "    border-width: 2px;\n"
                                     "    border-radius: 10px;\n"
                                     "    border-color: rgb(0, 0, 0);\n"
                                     "    font: bold 14px;\n"
                                     "    min-width: 10em;\n"
                                     "    padding: 6px;")
        self.titleEdit.setObjectName("titleEdit")
        self.horizontalLayout_3.addWidget(self.titleEdit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem7)
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                 "    border-style: outset;\n"
                                 "    border-width: 2px;\n"
                                 "    border-radius: 10px;\n"
                                 "    border-color: rgb(0, 0, 0);\n"
                                 "    font: bold 14px;\n"
                                 "    min-width: 10em;\n"
                                 "    padding: 6px;")
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.textEdit = QtWidgets.QLineEdit(self.page_2)
        self.textEdit.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                    "    border-style: outset;\n"
                                    "    border-width: 2px;\n"
                                    "    border-radius: 10px;\n"
                                    "    border-color: rgb(0, 0, 0);\n"
                                    "    font: bold 14px;\n"
                                    "    min-width: 10em;\n"
                                    "    padding: 6px;")
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_4.addWidget(self.textEdit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.rememberEventCheckBox = QtWidgets.QCheckBox(self.page_2)
        self.rememberEventCheckBox.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                                 "    border-style: outset;\n"
                                                 "    border-width: 2px;\n"
                                                 "    border-radius: 10px;\n"
                                                 "    border-color: rgb(0, 0, 0);\n"
                                                 "    font: bold 14px;\n"
                                                 "    min-width: 10em;\n"
                                                 "    padding: 6px;")
        self.rememberEventCheckBox.setChecked(True)
        self.rememberEventCheckBox.setObjectName("rememberEventCheckBox")
        self.horizontalLayout_6.addWidget(self.rememberEventCheckBox)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem11)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.page_2)
        self.dateTimeEdit.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                        "    border-style: outset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color: rgb(0, 0, 0);\n"
                                        "    font: bold 14px;\n"
                                        "    min-width: 10em;\n"
                                        "    padding: 6px;")
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.horizontalLayout_5.addWidget(self.dateTimeEdit)
        self.dateComboBox = QtWidgets.QComboBox(self.page_2)
        self.dateComboBox.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                        "    border-style: outset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color: rgb(0, 0, 0);\n"
                                        "    font: bold 14px;\n"
                                        "    min-width: 10em;\n"
                                        "    padding: 6px;")
        self.dateComboBox.setObjectName("dateComboBox")
        self.horizontalLayout_5.addWidget(self.dateComboBox)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem13)
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                   "    border-style: outset;\n"
                                   "    border-width: 2px;\n"
                                   "    border-radius: 10px;\n"
                                   "    border-color: rgb(0, 0, 0);\n"
                                   "    font: bold 14px;\n"
                                   "    min-width: 10em;\n"
                                   "    padding: 6px;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.familyMembersComboBox = QtWidgets.QComboBox(self.page_2)
        self.familyMembersComboBox.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                                 "    border-style: outset;\n"
                                                 "    border-width: 2px;\n"
                                                 "    border-radius: 10px;\n"
                                                 "    border-color: rgb(0, 0, 0);\n"
                                                 "    font: bold 14px;\n"
                                                 "    min-width: 10em;\n"
                                                 "    padding: 6px;")
        self.familyMembersComboBox.setObjectName("familyMembersComboBox")
        self.horizontalLayout_7.addWidget(self.familyMembersComboBox)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem15)
        self.addButton = QtWidgets.QPushButton(self.page_2)
        self.addButton.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                     "    border-style: outset;\n"
                                     "    border-width: 2px;\n"
                                     "    border-radius: 10px;\n"
                                     "    border-color: rgb(0, 0, 0);\n"
                                     "    font: bold 14px;\n"
                                     "    min-width: 10em;\n"
                                     "    padding: 6px;")
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_8.addWidget(self.addButton)
        self.cancelButton = QtWidgets.QPushButton(self.page_2)
        self.cancelButton.setStyleSheet("    background-color: rgb(156, 231, 255);\n"
                                        "    border-style: outset;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color: rgb(0, 0, 0);\n"
                                        "    font: bold 14px;\n"
                                        "    min-width: 10em;\n"
                                        "    padding: 6px;")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_8.addWidget(self.cancelButton)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding,
                                             QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum,
                                             QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem17)
        self.verticalLayout_3.setStretch(9, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Семейный календарь"))
        self.addFamilyMemberButton.setText(_translate("MainWindow", "Добавить члена семьи"))
        self.changeColorFamilyMember.setText(_translate("MainWindow", "Изменить цвет члена семьи"))
        self.removeFamilyMember.setText(_translate("MainWindow", "Удалить члена семьи"))
        self.addEventButton.setText(_translate("MainWindow", "Добавить событие"))
        self.toExcelButton.setText(_translate("MainWindow", "Преобразовать в excel"))
        self.label_4.setText(_translate("MainWindow", "Добавить событие"))
        self.radioButton.setText(_translate("MainWindow", "Одноразовое"))
        self.radioButton_2.setText(_translate("MainWindow", "Регулярное"))
        self.label_2.setText(_translate("MainWindow", "Загаловок события"))
        self.label.setText(_translate("MainWindow", "Текст события"))
        self.rememberEventCheckBox.setText(_translate("MainWindow", "Напоминать о событии"))
        self.label_3.setText(_translate("MainWindow", "К какому члену семьи событие относится"))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
        self.cancelButton.setText(_translate("MainWindow", "Отмена"))
